version: "3.7"
services:
  watchtower:
    image: containrrr/watchtower
    command:
      - "--label-enable"
      - "--internal"
      - "30"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    build: .
    ports:
      - "10000:4567"
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
    depends_on:
      - db
    command: >
      sh -c "npx prisma migrate deploy && pm2-runtime dist/app.js"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Fahrenheit451;
      POSTGRES_DB: fast-backend
    ports:
      - "5432:5432"
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

volumes:
  postgres_data:
