version: "3.7"
services:
  web:
    build: .
    ports:
      - "10000:4567"
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
    depends_on:
      - db
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
volumes:
  postgres_data:
