version: "3.7"
services:
  web:
    build: .
    ports:
      - "10000:4567"
    volumes:
      - .:/app
    environment:
      NODE_ENV: production
    depends_on:
      - db
    command: >
      sh -c "npx prisma migrate deploy && pm2-runtime dist/app.js"
  db:
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Fahrenheit451;
      POSTGRES_DB: fast-backend
    ports:
      - "5432:5432"

volumes:
  postgres_data:
